name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Curl traffic?
      run: |
        curl --url https://api.github.com/repos/suyashkumar/ssl-proxy/traffic/views?per=day --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
  
